# Generated by Django 3.0.7 on 2020-08-10 23:28

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('door', '0001_initial'),
    ]

    operations = [
        migrations.AlterModelOptions(
            name='config',
            options={'verbose_name': 'Door configuration'},
        ),
        migrations.AlterModelOptions(
            name='state',
            options={'verbose_name': 'Door state'},
        ),
        migrations.AddField(
            model_name='state',
            name='is_manually_closed',
            field=models.BooleanField(default=False),
        ),
    ]
